---
- name: Ensure HTTPd and PHP are installed
  yum:
    name: '{{ item }}'
    state: present
  become: True
  with_items:
  - httpd
  - php
  - php-mysql

- name: Ensure FirewallD will accept HTTP connections
  firewalld:
    port: 80/tcp
    permanent: True
    state: enabled
    immediate: True
  become: True

- name: Ensure HTTPd is running and enabled
  service:
    name: httpd
    state: started
    enabled: True
  become: True

- name: Ensure index.php is current
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
  become: True
